services:
  ai:
    container_name: ai
    build: ./AI
    ports:
      - "8000:8000"
    volumes:
      - ./AI:/app
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/best-hacks:/app
      - /app/node_modules
  database:
    container_name: database
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hackyeah
      POSTGRES_USER: hackyeah
      POSTGRES_PASSWORD: hackyeah
networks:
  default:
    name: "hackyeah2024_network"
