services:
  ai:
    container_name: ai
    build: ./AI
    ports:
      - "8000:8000"
    volumes:
      - ./AI:/app
    depends_on:
      - database
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/best-hacks:/app
      - /app/node_modules
  database:
    container_name: database
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: besthacks
      POSTGRES_USER: besthacks
      POSTGRES_PASSWORD: besthacks
networks:
  default:
    name: "BestHacks_network"
